local RS = RoomShape

MinimapAPI.RoomShapeFrames = {
	[RS.ROOMSHAPE_1x1] = 0,
	[RS.ROOMSHAPE_1x2] = 3,
	[RS.ROOMSHAPE_2x1] = 5,
	[RS.ROOMSHAPE_2x2] = 7,
	[RS.ROOMSHAPE_IH] = 1,
	[RS.ROOMSHAPE_IIH] = 6,
	[RS.ROOMSHAPE_IV] = 2,
	[RS.ROOMSHAPE_IIV] = 4,
	[RS.ROOMSHAPE_LBR] = 11,
	[RS.ROOMSHAPE_LTL] = 8,
	[RS.ROOMSHAPE_LTR] = 9,
	[RS.ROOMSHAPE_LBL] = 10,
}

MinimapAPI.RoomShapeGridSizes = {
	[RS.ROOMSHAPE_1x1] = Vector(1,1),
	[RS.ROOMSHAPE_1x2] = Vector(1,2),
	[RS.ROOMSHAPE_2x1] = Vector(2,1),
	[RS.ROOMSHAPE_2x2] = Vector(2,2),
	[RS.ROOMSHAPE_IH] = Vector(1,1),
	[RS.ROOMSHAPE_IIH] = Vector(2,1),
	[RS.ROOMSHAPE_IV] = Vector(1,1),
	[RS.ROOMSHAPE_IIV] = Vector(1,2),
	[RS.ROOMSHAPE_LBR] = Vector(2,2),
	[RS.ROOMSHAPE_LTL] = Vector(2,2),
	[RS.ROOMSHAPE_LTR] = Vector(2,2),
	[RS.ROOMSHAPE_LBL] = Vector(2,2),
}


MinimapAPI.RoomShapePositions = {
	[RS.ROOMSHAPE_1x1] = {Vector(0,0)},
	[RS.ROOMSHAPE_1x2] = {Vector(0,0),Vector(0,1)},
	[RS.ROOMSHAPE_2x1] = {Vector(0,0),Vector(1,0)},
	[RS.ROOMSHAPE_2x2] = {Vector(0,0),Vector(1,0),Vector(0,1),Vector(1,1)},
	[RS.ROOMSHAPE_IH] = {Vector(0,0)},
	[RS.ROOMSHAPE_IIH] = {Vector(0,0),Vector(1,0)},
	[RS.ROOMSHAPE_IV] = {Vector(0,0)},
	[RS.ROOMSHAPE_IIV] = {Vector(0,0),Vector(0,1)},
	[RS.ROOMSHAPE_LBR] = {Vector(0,0),Vector(1,0),Vector(0,1)},
	[RS.ROOMSHAPE_LTL] = {Vector(1,0),Vector(0,1),Vector(1,1)},
	[RS.ROOMSHAPE_LTR] = {Vector(0,0),Vector(0,1),Vector(1,1)},
	[RS.ROOMSHAPE_LBL] = {Vector(0,0),Vector(1,0),Vector(1,1)},
}

MinimapAPI.RoomShapeIconPositions = {
	[1] = {
		[RS.ROOMSHAPE_1x1] = {Vector(0,0)},
		[RS.ROOMSHAPE_1x2] = {Vector(0,0.5)},
		[RS.ROOMSHAPE_2x1] = {Vector(0.5,0)},
		[RS.ROOMSHAPE_2x2] = {Vector(0.5,0.5)},
		[RS.ROOMSHAPE_IH] = {Vector(0,0)},
		[RS.ROOMSHAPE_IIH] = {Vector(0.5,0)},
		[RS.ROOMSHAPE_IV] = {Vector(0,0)},
		[RS.ROOMSHAPE_IIV] = {Vector(0,0.5)},
		[RS.ROOMSHAPE_LBR] = {Vector(0,0),Vector(1,0),Vector(0,1)},
		[RS.ROOMSHAPE_LTL] = {Vector(1,0),Vector(0,1),Vector(1,1)},
		[RS.ROOMSHAPE_LTR] = {Vector(0,0),Vector(0,1),Vector(1,1)},
		[RS.ROOMSHAPE_LBL] = {Vector(0,0),Vector(1,0),Vector(1,1)},
	},
	[2] = {
		[RS.ROOMSHAPE_1x1] = {Vector(0,0)},
		[RS.ROOMSHAPE_1x2] = {Vector(0,0),Vector(0,1)},
		[RS.ROOMSHAPE_2x1] = {Vector(0,0),Vector(1,0)},
		[RS.ROOMSHAPE_2x2] = {Vector(0,0),Vector(1,0),Vector(0,1),Vector(1,1)},
		[RS.ROOMSHAPE_IH] = {Vector(0,0)},
		[RS.ROOMSHAPE_IIH] = {Vector(0,0),Vector(1,0)},
		[RS.ROOMSHAPE_IV] = {Vector(0,0)},
		[RS.ROOMSHAPE_IIV] = {Vector(0,0),Vector(0,1)},
		[RS.ROOMSHAPE_LBR] = {Vector(0,0),Vector(1,0),Vector(0,1)},
		[RS.ROOMSHAPE_LTL] = {Vector(1,0),Vector(0,1),Vector(1,1)},
		[RS.ROOMSHAPE_LTR] = {Vector(0,0),Vector(0,1),Vector(1,1)},
		[RS.ROOMSHAPE_LBL] = {Vector(0,0),Vector(1,0),Vector(1,1)},
	},
}

MinimapAPI.LargeRoomShapeIconPositions = {
	[1] = {
		[RS.ROOMSHAPE_1x1] = {Vector(0.25,0.25)},
		[RS.ROOMSHAPE_1x2] = {Vector(0.25,0.75)},
		[RS.ROOMSHAPE_2x1] = {Vector(0.75,0.25)},
		[RS.ROOMSHAPE_2x2] = {Vector(0.75,0.75)},
		[RS.ROOMSHAPE_IH] = {Vector(0.25,0.25)},
		[RS.ROOMSHAPE_IIH] = {Vector(0.75,0.25)},
		[RS.ROOMSHAPE_IV] = {Vector(0.25,0.25)},
		[RS.ROOMSHAPE_IIV] = {Vector(0.25,0.75)},
		[RS.ROOMSHAPE_LBR] = {Vector(0.25,0.25)},
		[RS.ROOMSHAPE_LTL] = {Vector(1.25,1.25)},
		[RS.ROOMSHAPE_LTR] = {Vector(0.25,1.25)},
		[RS.ROOMSHAPE_LBL] = {Vector(1.25,0.25)},
	},
	[2] = {
		[RS.ROOMSHAPE_1x1] = {Vector(0,0),Vector(0.5,0),Vector(0,0.5),Vector(0.5,0.5)},
		[RS.ROOMSHAPE_1x2] = {Vector(0,0.5),Vector(0.5,1),Vector(0,1),Vector(0.5,1)},
		[RS.ROOMSHAPE_2x1] = {Vector(0.5,0),Vector(1,0),Vector(0.5,0.5),Vector(1,0.5)},
		[RS.ROOMSHAPE_2x2] = {Vector(0.5,0.5),Vector(1,0.5),Vector(0.5,1),Vector(1,1)},
		[RS.ROOMSHAPE_IH] = {Vector(0,0),Vector(0.5,0),Vector(0,0.5),Vector(0.5,0.5)},
		[RS.ROOMSHAPE_IIH] = {Vector(0.5,0),Vector(1,0),Vector(0.5,0.5),Vector(1,0.5)},
		[RS.ROOMSHAPE_IV] = {Vector(0,0),Vector(0.5,0),Vector(0,0.5),Vector(0.5,0.5)},
		[RS.ROOMSHAPE_IIV] = {Vector(0,0.5),Vector(0.5,1),Vector(0,1),Vector(0.5,1)},
		[RS.ROOMSHAPE_LBR] = {Vector(0,0),Vector(0.5,0),Vector(0,0.5),Vector(0.5,0.5)},
		[RS.ROOMSHAPE_LTL] = {Vector(1,1),Vector(1.5,1),Vector(1,1.5),Vector(1.5,1.5)},
		[RS.ROOMSHAPE_LTR] = {Vector(0,1),Vector(0.5,1),Vector(0,1.5),Vector(0.5,1.5)},
		[RS.ROOMSHAPE_LBL] = {Vector(0,0),Vector(0.5,0),Vector(0,0.5),Vector(0.5,0.5)},
	},
}

MinimapAPI.RoomTypeIconIDs = {
	nil,
    "Shop",
    nil,
    "TreasureRoom",
    "Boss",
    "Miniboss",
    "SecretRoom",
    "SuperSecretRoom",
    "Arcade",
    "CurseRoom",
    "AmbushRoom",
    "Library",
    "SacrificeRoom",
    nil,
    "AngelRoom",
    nil,
    "BossAmbushRoom",
    "IsaacsRoom",
    "BarrenRoom",
    "ChestRoom",
    "DiceRoom",
    nil,
    "GreedExit",
    "TreasureRoomGreed"
}

MinimapAPI.UnknownRoomTypeIconIDs = {
	nil,
    "LockedRoom",
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    "LockedRoom",
    nil,
    nil,
    nil,
    nil,
    nil,
    "LockedRoom",
    "LockedRoom",
    "LockedRoom",
    "LockedRoom",
    nil,
    nil,
    nil,
}

local function notCollected(pickup) return not pickup:GetSprite():IsPlaying("Collect") end
local function chestNotCollected(pickup) return pickup.SubType ~= 0 end

MinimapAPI.PickupIconList = {
	{ID="WhiteHeart",anim="IconWhiteHeart",type=5,variant=10,subtype=4,call=notCollected,icongroup="hearts",priority=10800},
	{ID="GoldHeart",anim="IconGoldHeart",type=5,variant=10,subtype=7,call=notCollected,icongroup="hearts",priority=10700},
	{ID="BoneHeart",anim="IconBoneHeart",type=5,variant=10,subtype=11,call=notCollected,icongroup="hearts",priority=10600},
	{ID="BlackHeart",anim="IconBlackHeart",type=5,variant=10,subtype=6,call=notCollected,icongroup="hearts",priority=10500},
	{ID="BlueHeart",anim="IconBlueHeart",type=5,variant=10,subtype=3,call=notCollected,icongroup="hearts",priority=10400},
	{ID="BlendedHeart",anim="IconBlendedHeart",type=5,variant=10,subtype=10,call=notCollected,icongroup="hearts",priority=10300},
	{ID="HalfBlueHeart",anim="IconHalfBlueHeart",type=5,variant=10,subtype=8,call=notCollected,icongroup="hearts",priority=10200},
	{ID="Heart",anim="IconHeart",type=5,variant=10,subtype=1,call=notCollected,icongroup="hearts",priority=10100},
	{ID="HalfHeart",anim="IconHalfHeart",type=5,variant=10,subtype=2,call=notCollected,icongroup="hearts",priority=10000},
	{ID="Item",anim="IconItem",type=5,variant=100,subtype=-1,call=function(pickup) return pickup.SubType ~= 0 end,icongroup="collectibles",priority=9000},
	{ID="Trinket",anim="IconTrinket",type=5,variant=350,subtype=-1,icongroup="collectibles",priority=8000},
	{ID="EternalChest",anim="IconEternalChest",type=5,variant=53,subtype=-1,call=chestNotCollected,icongroup="chests",priority=7500},
	{ID="GoldChest",anim="IconGoldChest",type=5,variant=60,subtype=-1,call=chestNotCollected,icongroup="chests",priority=7400},
	{ID="RedChest",anim="IconRedChest",type=5,variant=360,subtype=-1,call=chestNotCollected,icongroup="chests",priority=7300},
	{ID="Chest",anim="IconChest",type=5,variant=50,subtype=-1,call=chestNotCollected,icongroup="chests",priority=7200},
	{ID="StoneChest",anim="IconStoneChest",type=5,variant=51,call=chestNotCollected,subtype=-1,icongroup="chests",priority=7100},
	{ID="SpikedChest",anim="IconSpikedChest",type=5,variant=52,call=chestNotCollected,subtype=-1,icongroup="chests",priority=7000},
	{ID="Pill",anim="IconPill",type=5,variant=70,subtype=-1,call=notCollected,icongroup="pills",priority=6000},
	{ID="Key",anim="IconKey",type=5,variant=30,subtype=-1,call=notCollected,icongroup="keys",priority=5000},
	{ID="Bomb",anim="IconBomb",type=5,variant=40,subtype=-1,call=notCollected,icongroup="bombs",priority=4000},
	{ID="Coin",anim="IconCoin",type=5,variant=20,subtype=-1,call=notCollected,icongroup="coins",priority=3000},
	{ID="Battery",anim="IconBattery",type=5,variant=90,subtype=-1,call=notCollected,icongroup="batteries",priority=2000},
	{ID="Card",anim="IconCard",type=5,variant=300,subtype=-1,call=notCollected,icongroup="cards",priority=1000},
	{ID="Slot",anim="IconSlot",type=6,variant=-1,subtype=-1,call=notCollected,icongroup="slots",priority=0},
}

MinimapAPI.IconList = {
	{ID="Shop",anim="IconShop",frame=0},
	{ID="TreasureRoom",anim="IconTreasureRoom",frame=0},
    {ID="Boss",anim="IconBoss",frame=0},
    {ID="Miniboss",anim="IconMiniboss",frame=0},
    {ID="SecretRoom",anim="IconSecretRoom",frame=0},
    {ID="SuperSecretRoom",anim="IconSuperSecretRoom",frame=0},
    {ID="Arcade",anim="IconArcade",frame=0},
    {ID="CurseRoom",anim="IconCurseRoom",frame=0},
    {ID="AmbushRoom",anim="IconAmbushRoom",frame=0},
    {ID="Library",anim="IconLibrary",frame=0},
    {ID="SacrificeRoom",anim="IconSacrificeRoom",frame=0},
    {ID="AngelRoom",anim="IconAngelRoom",frame=0},
    {ID="BossAmbushRoom",anim="IconBossAmbushRoom",frame=0},
    {ID="IsaacsRoom",anim="IconIsaacsRoom",frame=0},
    {ID="BarrenRoom",anim="IconBarrenRoom",frame=0},
    {ID="ChestRoom",anim="IconChestRoom",frame=0},
    {ID="DiceRoom",anim="IconDiceRoom",frame=0},
    {ID="GreedExit",anim="IconGreedExit",frame=0},
    {ID="TreasureRoomGreed",anim="IconTreasureRoomGreed",frame=0},
    {ID="LockedRoom",anim="IconLockedRoom",frame=0},
}